[package]
name = "counter"
version = "1.0.0"
authors = []

[addresses]
counter_addr='7e94dcde73c5fae22ffe1519c0f374b540c7fcb641110e3a9be7d87adc0853ff'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
